jQuery(function($){var contact={message:null,init:function(){$('#contact-form input.contact, #contact-form a.contact, .division,.division1').click(function(e){e.preventDefault();$.get("DivisionEditajax.php",function(data){$(data).modal({closeHTML:"<a href='#' title='Close' class='modal-close'>x</a>",position:["15%",],overlayId:'contact-overlay',containerId:'contact-container',onOpen:contact.open,onShow:contact.show,onClose:contact.close});});});},open:function(dialog){var h=280;if($('#contact-subject').length){h+=26;}
if($('#contact-cc').length){h+=22;}
var title=$('#contact-container .contact-title').html();$('#contact-container .contact-title').html('Loading...');dialog.overlay.fadeIn(200,function(){dialog.container.fadeIn(200,function(){dialog.data.fadeIn(200,function(){$('#contact-container .contact-content').animate({height:h},function(){$('#contact-container .contact-title').html(title);$('#contact-container form').fadeIn(200,function(){$('#contact-container #contact-name').focus();$('#contact-container .contact-cc').click(function(){var cc=$('#contact-container #contact-cc');cc.is(':checked')?cc.attr('checked',''):cc.attr('checked','checked');});});});});});});},show:function(dialog){$('#contact-container .contact-send').click(function(e){e.preventDefault();if(contact.validate()){var msg=$('#contact-container .contact-message');msg.fadeOut(function(){msg.removeClass('contact-error').empty();});$('#contact-container .contact-title').html('Sending...');$('#contact-container form').fadeOut(200);$('#contact-container .contact-content').animate({height:'80px'},function(){$('#contact-container .contact-loading').fadeIn(200,function(){$.ajax({url:'DivisionEditajax.php',data:$('#contact-container form').serialize()+'&action=send',type:'post',cache:false,dataType:'html',success:function(data){$('#contact-container .contact-loading').fadeOut(200,function(){$('#contact-container .contact-title').html('Thank you!');msg.html(data).fadeIn(200);});},error:contact.error});});});}
else{if($('#contact-container .contact-message:visible').length>0){var msg=$('#contact-container .contact-message div');msg.fadeOut(200,function(){msg.empty();contact.showError();msg.fadeIn(200);});}
else{$('#contact-container .contact-message').animate({height:'30px'},contact.showError);}}});},close:function(dialog){$.ajax({url:'getDivision.php',type:'post',cache:false,dataType:'html',success:function(data){$('.fDivisionId').html(data);}});$('#contact-container .contact-message').fadeOut();$('#contact-container .contact-title').html('Goodbye...');$('#contact-container form').fadeOut(200);$('#contact-container .contact-content').animate({height:40},function(){dialog.data.fadeOut(200,function(){dialog.container.fadeOut(200,function(){dialog.overlay.fadeOut(200,function(){$.modal.close();});});});});},error:function(xhr){alert(xhr.statusText);},validate:function(){contact.message='';if(!$('#contact-container #contact-name').val()){contact.message+='Name is required. ';}
if(!$('#contact-container #contact-lookup').val()){contact.message+='Lookup is required. ';}
if(contact.message.length>0){return false;}
else{return true;}},validateEmail:function(email){var at=email.lastIndexOf("@");if(at<1||(at+1)===email.length)
return false;if(/(\.{2,})/.test(email))
return false;var local=email.substring(0,at);var domain=email.substring(at+1);if(local.length<1||local.length>64||domain.length<4||domain.length>255)
return false;if(/(^\.|\.$)/.test(local)||/(^\.|\.$)/.test(domain))
return false;if(!/^"(.+)"$/.test(local)){if(!/^[-a-zA-Z0-9!#$%*\/?|^{}`~&'+=_\.]*$/.test(local))
return false;}
if(!/^[-a-zA-Z0-9\.]*$/.test(domain)||domain.indexOf(".")===-1)
return false;return true;},showError:function(){$('#contact-container .contact-message').html($('<div class="contact-error"></div>').append(contact.message)).fadeIn(200);}};contact.init();});